# Generated by Django 2.0.7 on 2018-08-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProduct',
            fields=[
                ('account', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=16)),
                ('highest_price', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('lowest_price', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('bbn_price', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='单次调用价格(BBN)')),
                ('limit_count', models.IntegerField()),
                ('used_count', models.IntegerField()),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField()),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'account_product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('fee_type', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('service_method', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('source', models.CharField(max_length=16)),
                ('status', models.BooleanField()),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_category',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='accountproduct',
            unique_together={('account', 'product')},
        ),
    ]
