# Generated by Django 2.0.7 on 2018-08-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=16, verbose_name='账号')),
                ('product', models.CharField(max_length=16, verbose_name='产品编码')),
                ('request_count', models.IntegerField(verbose_name='请求次数')),
                ('bill_count', models.IntegerField(verbose_name='计费次数')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='计费金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('day_at', models.DateField(verbose_name='创建时间')),
            ],
            options={
                'db_table': 'bill_daily',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BillMonthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=16, verbose_name='账号')),
                ('product', models.CharField(max_length=16, verbose_name='产品编码')),
                ('request_count', models.IntegerField(verbose_name='请求次数')),
                ('bill_count', models.IntegerField(verbose_name='计费次数')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='计费金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('month_at', models.DateField(verbose_name='月份')),
            ],
            options={
                'db_table': 'bill_monthly',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BillWeekly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=16, verbose_name='账号')),
                ('product', models.CharField(max_length=16, verbose_name='产品编码')),
                ('request_count', models.IntegerField(verbose_name='请求次数')),
                ('bill_count', models.IntegerField(verbose_name='计费次数')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='计费金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('week_in_year', models.IntegerField(verbose_name='自然周序数')),
                ('begin_day_at', models.DateField(verbose_name='周开始日期')),
                ('end_day_at', models.DateField(verbose_name='周结束日期')),
            ],
            options={
                'db_table': 'bill_weekly',
                'managed': True,
            },
        ),
    ]
