# Generated by Django 2.0.7 on 2018-07-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='任务描述')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('question_price', models.IntegerField(blank=True, null=True, verbose_name='题目单价')),
                ('question_count', models.IntegerField(blank=True, null=True, verbose_name='题目总量')),
                ('question_received', models.IntegerField(blank=True, null=True, verbose_name='已被领取的题目数量')),
            ],
            options={
                'verbose_name_plural': '任务',
                'db_table': 'tasks',
                'verbose_name': '任务',
            },
        ),
    ]
