# Generated by Django 2.0.7 on 2018-07-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='任务名称'),
        ),
    ]
