# Generated by Django 2.0.7 on 2018-07-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='imgs', verbose_name='图片'),
        ),
    ]
