# Generated by Django 2.0.7 on 2018-07-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20180731_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='question_received',
        ),
        migrations.AddField(
            model_name='task',
            name='received_count',
            field=models.IntegerField(default=0, verbose_name='已领取人数'),
        ),
    ]
