# Generated by Django 2.0.7 on 2018-08-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20180731_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='max_count',
            field=models.IntegerField(default=0, verbose_name='最大可领取人数'),
        ),
    ]
