# Generated by Django 2.0.7 on 2018-08-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_task_is_file_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.IntegerField(default=6, verbose_name='创建人ID'),
        ),
    ]
