# Generated by Django 2.0.7 on 2018-08-27 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_task_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='attachment_id',
        ),
    ]
