# Generated by Django 2.0.7 on 2018-07-31 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': '用户反馈', 'verbose_name_plural': '用户反馈'},
        ),
    ]
