# Generated by Django 2.0.7 on 2018-07-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180731_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='passed_count',
            field=models.IntegerField(db_index=True, default=0, verbose_name='审核通过条数'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='passed_reward_count',
            field=models.IntegerField(default=0, verbose_name='奖励数量'),
        ),
    ]
