# Generated by Django 2.0.7 on 2018-07-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180731_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='status',
            field=models.CharField(blank=True, choices=[('待提交', '待提交'), ('审核中', '审核中'), ('审核通过', '审核通过'), ('审核未通过', '审核未通过'), ('到期未完成', '到期未完成')], db_index=True, max_length=255, null=True, verbose_name='状态'),
        ),
    ]
