# Generated by Django 2.0.7 on 2018-08-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180731_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='is_file_answer',
            field=models.BooleanField(default=False, verbose_name='答案是否需要上传文件'),
        ),
    ]
