# Generated by Django 2.0.7 on 2018-08-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_usertask_is_file_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserValidateCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户id')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='发送邮箱')),
                ('code', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
