# Generated by Django 2.0.7 on 2018-08-03 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_uservalidatecode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uservalidatecode',
            options={'verbose_name': '用户验证码', 'verbose_name_plural': '用户验证码'},
        ),
        migrations.AlterModelTable(
            name='uservalidatecode',
            table='validate_codes',
        ),
    ]
