# Generated by Django 2.0.7 on 2018-08-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20180803_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwithdraw',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='提现地址'),
        ),
    ]
