# Generated by Django 2.0.7 on 2018-08-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_uservalidatecode_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='finished_count',
            field=models.IntegerField(default=0, verbose_name='完成数量'),
        ),
    ]
