# Generated by Django 2.0.7 on 2018-08-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_usertask_finished_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='status',
            field=models.CharField(blank=True, choices=[('待提交', '待提交'), ('审核中', '审核中'), ('审核完毕', '审核完毕'), ('已过期', '已过期')], db_index=True, max_length=255, null=True, verbose_name='状态'),
        ),
    ]
