# Generated by Django 2.0.7 on 2018-08-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20180810_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='手机号'),
        ),
    ]
