# Generated by Django 2.0.7 on 2018-08-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_userprofile_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApplyInterfaceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='产品名')),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系人姓名')),
                ('contact_mobile', models.CharField(blank=True, max_length=255, null=True, verbose_name='手机号')),
                ('expected_dosage', models.CharField(blank=True, max_length=255, null=True, verbose_name='预计用量')),
            ],
            options={
                'verbose_name_plural': '用户申请调用信息',
                'verbose_name': '用户申请调用信息',
                'db_table': 'apply_interface_info',
            },
        ),
    ]
