# Generated by Django 2.0.7 on 2018-08-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_userapplyinterfaceinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='customer_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='客户ID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='用户类型'),
        ),
    ]
