# Generated by Django 2.0.7 on 2018-08-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceCooperationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='数据名称')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='数据类别')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='数据描述')),
                ('price', models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True, verbose_name='价格')),
                ('price_property', models.CharField(blank=True, max_length=255, null=True, verbose_name='价格属性')),
                ('data_amount', models.IntegerField(blank=True, null=True, verbose_name='数据量(条)')),
                ('data_norm', models.TextField(blank=True, null=True, verbose_name='数据规范')),
                ('data_fields', models.TextField(blank=True, null=True, verbose_name='数据字段')),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系人姓名')),
                ('contact_mobile', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系人手机号')),
            ],
            options={
                'db_table': 'data_source_cooperation_info',
                'verbose_name_plural': '数据源合作信息',
                'verbose_name': '数据源合作信息',
            },
        ),
    ]
