# Generated by Django 2.0.7 on 2018-08-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasourcecooperationinfo',
            name='price_property',
        ),
        migrations.AlterField(
            model_name='datasourcecooperationinfo',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='价格'),
        ),
    ]
