# Generated by Django 2.0.7 on 2018-08-22 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0002_auto_20180822_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasourcecooperationinfo',
            name='category',
        ),
        migrations.RemoveField(
            model_name='datasourcecooperationinfo',
            name='data_norm',
        ),
        migrations.RemoveField(
            model_name='datasourcecooperationinfo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='datasourcecooperationinfo',
            name='price',
        ),
    ]
