# Generated by Django 2.0.7 on 2018-08-21 02:42

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='接口名称')),
                ('price', models.IntegerField(verbose_name='每次调用价格(BBN)')),
                ('info', models.TextField(verbose_name='描述')),
                ('desc', models.CharField(max_length=255, verbose_name='接口介绍')),
                ('scene', models.CharField(max_length=255, verbose_name='适用场景')),
            ],
            options={
                'verbose_name_plural': '接口',
                'db_table': 'interfaces',
                'verbose_name': '接口',
            },
        ),
        migrations.CreateModel(
            name='InterfaceExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('interface_id', models.IntegerField(verbose_name='接口id')),
                ('is_res', models.BooleanField(default=False, verbose_name='是否为返回示例')),
                ('content', jsonfield.fields.JSONField(verbose_name='示例内容')),
                ('e_type', models.CharField(max_length=255, verbose_name='类型')),
            ],
            options={
                'verbose_name_plural': '接口示例（请求，返回）',
                'db_table': 'interface_examples',
                'verbose_name': '接口示例（请求，返回）',
            },
        ),
        migrations.CreateModel(
            name='InterfaceParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('interface_id', models.IntegerField(verbose_name='接口id')),
                ('is_res', models.BooleanField(default=False, verbose_name='是否为返回参数')),
                ('name', models.CharField(max_length=255, verbose_name='参数名')),
                ('p_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='参数类型')),
                ('demand', models.CharField(blank=True, max_length=255, null=True, verbose_name='输入要求')),
                ('info', models.CharField(max_length=255, verbose_name='说明')),
            ],
            options={
                'verbose_name_plural': '接口参数',
                'db_table': 'interface_params',
                'verbose_name': '接口参数',
            },
        ),
    ]
