# Generated by Django 2.0.7 on 2018-08-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_auto_20180821_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfaceprofile',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='接口种类'),
        ),
        migrations.AddField(
            model_name='interfaceprofile',
            name='img',
            field=models.ImageField(default='', upload_to='', verbose_name='接口图片'),
            preserve_default=False,
        ),
    ]
