# Generated by Django 2.0.7 on 2018-07-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='detail_id',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='detail_type',
        ),
        migrations.AddField(
            model_name='question',
            name='attachment_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='附件id'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/answer/%Y/%m/%d', verbose_name='文件结果'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_url',
            field=models.FileField(blank=True, null=True, upload_to='uploads/question/%Y/%m/%d', verbose_name='文件结果'),
        ),
    ]
