# Generated by Django 2.0.7 on 2018-07-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20180731_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='状态'),
        ),
    ]
