# Generated by Django 2.0.7 on 2018-07-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20180731_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='file_url',
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_obj',
            field=models.FileField(blank=True, null=True, upload_to='static/download', verbose_name='文件结果'),
        ),
    ]
