# Generated by Django 2.0.7 on 2018-08-02 09:57

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='文本结果'),
        ),
    ]
