# Generated by Django 2.0.7 on 2018-08-02 12:23

import apps.util.wrapper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_auto_20180802_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.util.wrapper.answer_directory_path, verbose_name='文件结果'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.CharField(blank=True, choices=[('待审核', '待审核'), ('审核通过', '审核通过'), ('审核未通过', '审核未通过')], max_length=255, null=True, verbose_name='状态'),
        ),
    ]
