# Generated by Django 2.0.7 on 2018-08-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_auto_20180803_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
