# Generated by Django 2.0.7 on 2018-08-28 02:26

import apps.util.wrapper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0013_auto_20180827_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='created_by',
            field=models.IntegerField(default=6, verbose_name='创建人ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='question_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='题目ID'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='task_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='任务ID'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_obj',
            field=models.FileField(blank=True, null=True, upload_to=apps.util.wrapper.attachment_path, verbose_name='文件'),
        ),
    ]
