# Generated by Django 2.0.7 on 2018-08-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0014_auto_20180828_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='审核状态(answer类型)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('文件翻译', '文件翻译'), ('数据清洗', '数据清洗'), ('图片上传', '图片上传')], max_length=255, null=True, verbose_name='题目类型'),
        ),
    ]
