# Generated by Django 2.0.7 on 2018-09-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0015_auto_20180831_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='reviewer_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='审核人id(answer类型)'),
        ),
    ]
