# Generated by Django 2.0.7 on 2018-08-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('gateway_account', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='网关客户账户')),
                ('contact_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='联系人姓名')),
                ('contact_email', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='联系人邮箱')),
                ('contact_mobile', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='联系人手机号')),
                ('contact_address', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='联系人地址')),
                ('company_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='公司名称')),
                ('company_website', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='公司网址')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='状态')),
            ],
            options={
                'db_table': 'customers',
                'verbose_name_plural': '客户',
                'verbose_name': '客户',
            },
        ),
        migrations.CreateModel(
            name='CustomerAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('customer_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='客户ID')),
                ('attachment_id', models.IntegerField(db_index=True, verbose_name='附件ID')),
                ('attachment_type', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='附件类型')),
                ('status', models.CharField(max_length=255, verbose_name='状态')),
            ],
            options={
                'db_table': 'customer_attachments',
                'verbose_name_plural': '客户上传附件',
                'verbose_name': '客户上传附件',
            },
        ),
        migrations.CreateModel(
            name='CustomerBilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='客户ID')),
                ('interface_id', models.IntegerField(db_index=True, verbose_name='接口ID')),
                ('request_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='接口调用日期')),
                ('success_count', models.IntegerField(blank=True, null=True, verbose_name='接口成功调用次数')),
                ('bbn_cost', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='BBN消费数量')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'customer_billings',
                'verbose_name_plural': '客户接口查询日志报表',
                'verbose_name': '客户接口查询日志报表',
            },
        ),
        migrations.CreateModel(
            name='CustomerInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('customer_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='客户ID')),
                ('interface_id', models.IntegerField(verbose_name='接口ID')),
                ('bbn_price', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='单次调用价格(BBN)')),
                ('status', models.CharField(max_length=255, verbose_name='状态')),
            ],
            options={
                'db_table': 'customer_interfaces',
                'verbose_name_plural': '客户已开通接口',
                'verbose_name': '客户已开通接口',
            },
        ),
    ]
